<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.formation.films</groupId>
        <artifactId>gestion-films</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>films-service</artifactId>
    <name>Films - Service</name>

    <dependencies>
        <!-- Module domain -->
        <dependency>
            <groupId>com.formation.films</groupId>
            <artifactId>films-domain</artifactId>
        </dependency>

        <!-- Spring Data JPA (Hibernate inclus) -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>

        <!-- Tests : H2 + Spring Boot test -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>