spring:
  datasource:
    url: jdbc:h2:mem:films;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop   # recrée le schéma au démarrage (DEV ONLY)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true   # data.sql après les @Entity

    
  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true           # accessible sur http://localhost:8080/h2-console
      path: /h2-console